use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/dudehan/LCPodSpecs.git'

platform :ios, '9.0'

target 'LCModuleA_Example' do
#  pod 'LCModuleA', :path => '../'
  pod 'LCModuleA', '~> 0.3.0'
  target 'LCModuleA_Tests' do
    inherit! :search_paths

    
  end
end
